apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-emptydir
  labels:
    name: nginx
spec:
  volumes :
   - name: html
     emptyDir: {}
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name : html
          mountPath: /usr/share/nginx/html
          readOnly : true
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name : html-updater
      image : alpine
      command : ["/bin/sh", "-c"]
      args:
        - while true; do date >> /html/index.html;
            sleep 10; done      
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: html
          mountPath: /html
            